[project]
name = 'Special-Needs-Child-Services-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.billing-insurance]
path = 'contracts/billing-insurance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
